name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: "Test with Jekyll ${{ matrix.jekyll }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        jekyll: ["~> 3.9", "~> 4.2"]
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Set Up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.10
          bundler-cache: true
      - name: Run tests
        run: script/cibuild
